Class {
	#name : #Lizard,
	#superclass : #Object,
	#category : #'Ex_3'
}

{ #category : #'as yet unclassified' }
Lizard >> versus: aHand [
	^ aHand versusLizard
]

{ #category : #'as yet unclassified' }
Lizard >> versusLizard [
	^ 'Draw'
]

{ #category : #'as yet unclassified' }
Lizard >> versusPaper [
	^ 'Lizard'
]

{ #category : #'as yet unclassified' }
Lizard >> versusRock [
	^ 'Rock'
]

{ #category : #'as yet unclassified' }
Lizard >> versusScissors [
	^ 'Scissors'
]

{ #category : #'as yet unclassified' }
Lizard >> versusSpock [
	^ 'Lizard'
]
