Class {
	#name : #Paper,
	#superclass : #Object,
	#category : #'Ex_3'
}

{ #category : #'as yet unclassified' }
Paper >> versus: aHand [
	^ aHand versusPaper
]

{ #category : #'as yet unclassified' }
Paper >> versusLizard [
	^ 'Lizard'
]

{ #category : #'as yet unclassified' }
Paper >> versusPaper [
	^ 'Draw'
]

{ #category : #'as yet unclassified' }
Paper >> versusRock [
	^ 'Paper'
]

{ #category : #'as yet unclassified' }
Paper >> versusScissors [
	^ 'Scissors'
]

{ #category : #'as yet unclassified' }
Paper >> versusSpock [
	^ 'Paper'
]
