Class {
	#name : #Spock,
	#superclass : #Object,
	#category : #'Ex_3'
}

{ #category : #'as yet unclassified' }
Spock >> versus: aHand [

	^ aHand versusSpock
]

{ #category : #'as yet unclassified' }
Spock >> versusLizard [
	^ 'Lizard'
]

{ #category : #'as yet unclassified' }
Spock >> versusPaper [
	^ 'Paper'
]

{ #category : #'as yet unclassified' }
Spock >> versusRock [
	^ 'Spock'
]

{ #category : #'as yet unclassified' }
Spock >> versusScissors [
	^ 'Spock'
]

{ #category : #'as yet unclassified' }
Spock >> versusSpock [
	^ 'Draw'
]
